In [1]:
import pandas as pd
import os
cwd = os.getcwd()
locationMap = pd.read_excel("Loc_Mapping.xlsx",index_col=None)
demandMatrixOrig = pd.read_excel("Demand and Stock.xlsx",sheet_name="Demand")
stockMatrixOrig = pd.read_excel("Demand and Stock.xlsx",sheet_name="60AgedStock")
demandMatrix = pd.read_excel("Demand and Stock.xlsx",sheet_name="Demand")
stockMatrix = pd.read_excel("Demand and Stock.xlsx",sheet_name="60AgedStock")
locationMap.head()

,HPC,YKSS,PDSC,PILSS,DHSC,WWSS,BORSS,KOHSC,NAWSC,KOTSS,...,SEEDWSC,KALSS,KATKRSC,KURSC,KEGSC,KDYSC,KATGSC,KUNDSS,GLSC,MATSC
0,WWSS,GMSC,KALSS,DHSC,WWSS,DHSC,PILSS,DHSC,BORSS,HOMSC,...,NEGSC,KATKRSC,KALSS,KEGSC,KURSC,KATGSC,KDYSC,KATGSC,MATSC,GLSC
1,DHSC,KDWSC,KATKRSC,PDSC,KOHSC,KOHSC,DHSC,BORSS,KOHSC,THLSC,...,WATSC,PDSC,PDSC,KATGSC,KDYSC,KUNDSS,KUNDSS,KDYSC,KATKRSC,KATKRSC
2,KOHSC,KIRSS,PILSS,WWSS,BORSS,BORSS,KOHSC,WWSS,PILSS,NAWSC,...,MINWSC,PILSS,PILSS,KDYSC,KATGSC,KEGSC,KEGSC,KURSC,KALSS,KALSS
3,BATSC,MINWSC,DHSC,BORSS,PILSS,PILSS,WWSS,PILSS,WWSS,PILSS,...,KCHKSC,DHSC,DHSC,KUNDSS,YKSS,KURSC,KURSC,KEGSC,PDSC,PDSC
4,BORSS,SEEDWSC,WWSS,KOHSC,PDSC,PDSC,PDSC,NAWSC,DHSC,BORSS,...,GMSC,WWSS,WWSS,MINWSC,GMSC,YKSS,YKSS,MINWSC,PILSS,PILSS

In [2]:
locationMapOrder = locationMap.columns

In [3]:
demandMatrix.head()

,Item Code,plu_code,itm_desc,Item Category,AVG Price,BATSC,BORSS,DHSC,GLSC,GMSC,...,NAWSC,NEGSC,PDSC,PILSS,SEEDWSC,THLSC,WATSC,WWSS,YKSS,Grand Total
0,AB41011B,772676,FARLIN FEEDER PP140ML BOY,Baby Corner,1268.461,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,5
1,ADLP1218,826988,ARPICO DELUXE PILLOW 12 X 18 B,Baby Corner,708.040,0,0,6,0,0,...,0,4,0,7,0,8,0,6,2,99
2,ADLP1624,826986,ARPICO DELUXE PILLOW 16 X 24,Domestics,1085.270,30,0,40,0,0,...,0,0,0,20,10,10,20,15,0,259
3,ADLP1827,818769,ARPICO DELUX PILLOWS 18 X 27,Domestics,1236.160,30,0,40,0,0,...,0,0,0,0,20,8,0,0,0,231
4,ADLP2040,826987,ARPICO DELUXE PILLOW 20 X 40,Domestics,2025.450,0,0,2,0,0,...,0,2,0,0,4,0,5,0,0,31

In [4]:
stockMatrix.head()

,Item Code,plu_code,itm_desc,Item Category,AVG Price,BATSC,BORSS,DHSC,GLSC,GMSC,...,NAWSC,NEGSC,PDSC,PILSS,SEEDWSC,THLSC,WATSC,WWSS,YKSS,Grand Total
0,AB41011B,772676.0,FARLIN FEEDER PP140ML BOY,Baby Corner,1268.461,4.0,5.0,0.0,1.0,2.0,...,1.0,0.0,11.0,5.0,1.0,0.0,6.0,5.0,4.0,114.0
1,ADLP1218,826988.0,ARPICO DELUXE PILLOW 12 X 18 B,Baby Corner,708.040,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
2,ADLP1624,826986.0,ARPICO DELUXE PILLOW 16 X 24,Domestics,1085.270,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,ADLP1827,818769.0,ARPICO DELUX PILLOWS 18 X 27,Domestics,1236.160,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,12.0
4,ADLP2040,826987.0,ARPICO DELUXE PILLOW 20 X 40,Domestics,2025.450,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0

In [5]:
allItems = list(demandMatrixOrig['Item Code'])

In [6]:
stockMatrix.set_index('Item Code',inplace=True)

In [7]:
demandMatrix.set_index('Item Code',inplace=True)

In [8]:
demandMatrix.at['AB41011B','NAWSC']

5

In [9]:
stockMatrix.at['AB41011B','HPC']

3.0

In [10]:
for location in locationMapOrder:
    eachdfLoc = location
    hpc = demandMatrixOrig[['Item Code','plu_code','itm_desc','Item Category','AVG Price']].copy()
    locationOrderBySet= list(locationMap[eachdfLoc])
    for location in locationOrderBySet:
        hpc[location] = 0
    hpc.set_index('Item Code', inplace = True)
    for itemCode in allItems:
        onhstock = stockMatrix.at[itemCode,eachdfLoc]
        if(onhstock <=0):
            continue
        for location in locationOrderBySet:
            if location == eachdfLoc:
                continue
            outlet_demand = demandMatrix.at[itemCode,location]
            balance_demand= 0
            if outlet_demand <=0:
                continue
            if outlet_demand > onhstock:
                allocation = onhstock
                balance_demand = outlet_demand-onhstock
                onhstock = 0
            else:
                allocation = outlet_demand
                onhstock = onhstock-outlet_demand
                balance_demand = 0
            hpc.at[itemCode,location] = allocation
            stockMatrix.at[itemCode,eachdfLoc] = onhstock
            demandMatrix.at[itemCode,location] = balance_demand
    hpc['total_allocation'] = hpc[list(locationMap[eachdfLoc])].sum(axis=1)
    hpc['total_value'] = hpc['total_allocation']*hpc['AVG Price']
    hpc = hpc[hpc['total_allocation'] > 0]
    hpc.to_csv("allocation\\share\\"+ eachdfLoc +".csv")

In [11]:
stockMatrix.at['GRRG34012','YKSS']

0.0

In [12]:
demandMatrix.to_csv("balanced_demand.csv")

In [13]:
stockMatrix.to_csv("balanced_stock.csv")